import os
from datetime import datetime
from pathlib import Path
from typing import Any
from google import genai
from framework.workspace import Workspace, MissionSignal
from framework.agents.base import BaseAgent


class ReporterAgent(BaseAgent):
    """
    Reporting Agent: Compiles analysis findings into technical reports.
    """

    def __init__(self, name: str, workspace: Workspace, client: genai.Client, output_dir: str = "outputs/"):
        super().__init__(name, workspace, client)
        self.output_dir = Path(output_dir).resolve()
        self.output_dir.mkdir(exist_ok=True)

    def _setup_subscriptions(self):
        self.workspace.subscribe(MissionSignal.VERIFICATION_COMPLETE, self.handle_signal)

    def handle_signal(self, signal: MissionSignal, data: Any = None):
        if signal == MissionSignal.VERIFICATION_COMPLETE:
            self.logger.info("Reporting Agent triggered.")
            self.generate_report(
                data.get("insights", "No insights provided."),
                figures=data.get("figures", []),
            )

    def generate_report(self, insights: str, figures: list = None):
        """
        Formats and saves a technical Markdown report.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_filename = f"geophysical_report_{timestamp}.md"
        report_path = self.output_dir / report_filename

        state = self.workspace.state
        mission_id = state.mission_id if state else "N/A"

        figures_section = ""
        if figures:
            figures_section = "\n## Generated Figures\n"
            for fig in figures:
                figures_section += f"- `{fig}`\n"

        report_content = f"""# Geophysical Analysis Report
**Mission ID:** {mission_id}
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Mission Objective
{state.description if state else "N/A"}

## Data Sources
{", ".join(state.data_paths) if state and state.data_paths else "None"}
{figures_section}
## Analysis Insights
{insights}

---
*Generated by the Seismic Agent Multi-Agent System.*
"""
        
        try:
            with open(report_path, "w") as f:
                f.write(report_content)
            
            self.logger.info(f"Report successfully generated at: {report_path}")
            self.workspace.update_state(
                report_path=str(report_path),
                status="REPORT_GENERATED"
            )
            self.workspace.emit(MissionSignal.REPORT_GENERATED, data={"path": str(report_path)})
            
        except Exception as e:
            self.logger.error(f"Failed to save report: {e}")
            self.workspace.emit(MissionSignal.MISSION_FAILED, data={"error": str(e)})
